### PR TITLE
update notebook

### PR DESCRIPTION
**Pull request by qrtt1**
use the `primehub config generate-token` command to request API Token

### CODE REVIEW

**Comment by ggosiang** [comment]
regarding the new cell of `Request API Token`
should we use the URL `https://demo.aws.primehub.io` instead of `https://demo.aws.primehub.io/api/graphql`?
i

**Comment by qrtt1** [comment]
@ggosiang we could use any URL from the cluster, it will be tested from the SDK to find the correct one. so we could use the root URL :)

**Comment by ggosiang** [comment]
thanks for answering, I'd suggest using the root URL in the demo notebook

**Review by ggosiang — APPROVED** [review]

**Comment by popcornylu** [comment]
Please change the comment in the cell.

from
```
# Replace you API token
```

to

```
# Request the API token
```

image

**Pull request merged**
